# Generated by Django 2.0.4 on 2018-05-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
